# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{to_insane}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Ong"]
  s.date = %q{2011-02-08}
  s.description = %q{ToInsane allows you to convert strings and integers to a Base larger than the default max of 36 and use a custom character set}
  s.email = %q{ryanong@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/to_insane.rb",
    "test/test_to_insane.rb",
    "to_insane.gemspec"
  ]
  s.homepage = %q{http://github.com/ryanong/to_insane}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{ToInsane allows you to convert strings and integers to a Base larger than the default max of 36 and use a custom character set}
  s.test_files = [
    "test/test_to_insane.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

